language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: W8awBypqc+W/zU8M0schd09MfjIkZZOGHMzKo6zORiQMe7PxllDHr6YX/Qi9uVN22QVf3kqGumJKuK0H/sVPKKBTznrMjtHw4AXZvFvbtZxREeZhHd9Q/YiHEMke3l7gq8GePd4nTG3F9WZ2yr4eX9FeOFRZi98zKCl2KlFMh6aIlU7K7MdA81cDEYnqbDBy1U+i0TbBmsP9Yk2Tc2xtFta7sL0F5In1hrNxDzsK+5ch375mZzAq+P0YkfNANo6lO4VD7BlHzUOp4sStDYYcD9bAHImWI4YsnHuCgMnI/x8boAubXp1IhS4rR/Eiwg9sQStHq6roH4FPl6vEd4H19YAGzrysJAg0S+SC2adLGT9dbO6Crw0PIlXREPldPXehowr1U/HEAcC+VNjjiId9Wh1IstUIyPanbH0C4moL9JqOlSPSLcdwHilMR2rA4qQ/QTk0/63oe32r/8l3/xOSO+9m4EkI5WdfJsjn1LmgkVbBT1xScMvO3oVcTZ0Iehf50abvoCBixlH/laGyvJX2fP7IHBS4aRm9tAQqranFX+kQlJRXaBQ8BCFlDEcXNLkUFrgphAUSteACgy9ZD1jcPLgN+kt1UD5zSdrvE3EFBbZ5DZc4sOCs7LIB5OVKuU94oOoHh2E7mS8AMNdQoH3Z/AVPkRuEeY8c4oC30TTKMjc=
  file:
    - fs.img
    - xv6.img
  skip_cleanup: true
  on:
    repo: MiguelConcha22/xv6-public
    branch: project_3
    tags: true
